USE Training_Basic;
CREATE TABLE Trainer_info( Trainer_id VARCHAR(20) PRIMARY KEY, Salutation VARCHAR(7) NOT NULL, Trainer_Name VARCHAR(30) NOT NULL, Trainer_Location VARCHAR(30) NOT NULL, Trainer_Track VARCHAR(15) NOT NULL, Trainer_Qualification VARCHAR(100) NOT NULL, Trainer_Experience INT(11) NOT NULL, Trainer_Email VARCHAR(100) NOT NULL, Trainer_Password VARCHAR(20) NOT NULL, CONSTRAINT UC_Email UNIQUE (Trainer_Email) );

CREATE TABLE Module_Info( Module_Id VARCHAR(20) PRIMARY KEY, Module_Name VARCHAR(40), Module_Duration INT(11) );
CREATE TABLE Associate_Info( Associate_Id VARCHAR(20) PRIMARY KEY, Salutation VARCHAR(7) NOT NULL, Associate_Name VARCHAR(30) NOT NULL, Associate_Location VARCHAR(30) NOT NULL, Associate_Track VARCHAR(15) NOT NULL, Associate_Qualification VARCHAR(200) NOT NULL, Associate_Email VARCHAR(100) NOT NULL, Associate_Password VARCHAR(20) NOT NULL, CONSTRAINT UC_Email UNIQUE (Associate_Email) );
CREATE TABLE Associate_Status( Associate_Id VARCHAR(20), Module_Id VARCHAR(20), Batch_Id VARCHAR(20), Start_Date DATE NOT NULL, End_Date DATE NOT NULL, AFeedbackGiven BOOLEAN DEFAULT FALSE, TFeedbackGiven BOOLEAN DEFAULT FALSE, CONSTRAINT FK_Associate_Id FOREIGN KEY (Associate_Id) REFERENCES Associate_Info(Associate_Id), CONSTRAINT FK_Module_Id_1 FOREIGN KEY (Module_Id) REFERENCES Module_Info(Module_Id));
ALTER TABLE Associate_Status ADD COLUMN Trainer_Id VARCHAR(20);
ALTER TABLE Associate_Status ADD CONSTRAINT FK_Trainer_Id_ FOREIGN KEY (Trainer_Id) REFERENCES Trainer_Info(Trainer_Id);
INSERT INTO Trainer_Info(Trainer_Id, Salutation, Trainer_Name, Trainer_Location, Trainer_Track, Trainer_Qualification, Trainer_Experience, Trainer_Email, Trainer_Password) VALUES ('F001', 'Mr.', 'PANKAJ GHOSH', 'Pune', 'Java', 'Bachelor of Technology', 12, 'Pankaj.Ghosh@alliance.com', 'fac1@123'), ('F002', 'Mr.', 'SANJAY RADHAKRISHNAN', 'Bangalore', 'DotNet', 'Bachelor of Technology', 12,'Sanjay.Radhakrishnan@alliance.com', 'fac2@123'), ('F003', 'Mr.', 'VIJAY MATHUR', 'Chennai', 'Mainframe', 'Bachelor of Technology', 10, 'Vijay.Mathur@alliance.com', 'fac3@123'),('F004', 'Mrs.', 'NANDINI NAIR', 'Kolkata', 'Java', 'Master of Computer Applications', 9, 'Nandini.Nair@alliance.com', 'fac4@123'), ('F005', 'Miss.', 'ANITHA PAREKH', 'Hyderabad', 'Testing', 'Master of Computer Applications', 6, 'Anitha.Parekh@alliance.com', 'fac5@123');
INSERT INTO Associate_Info(Associate_Id, Salutation, Associate_Name, Associate_Location, Associate_Track, Associate_Qualification, Associate_Email, Associate_Password) VALUES('A001', 'Miss.', 'GAYATHRI NARAYANAN', 'Gurgaon', 'Java', 'Bachelor of Technology', 'Gayathri.Narayanan@hp.com', 'tne1@123'), ('A002', 'Mrs.', 'RADHIKA MOHAN', 'Kerala', 'Java', 'Bachelor of Engineering In Information Technology', 'Radhika.Mohan@cognizant.com', 'tne2@123'), ('A003', 'Mr.', 'KISHORE SRINIVAS', 'Chennai', 'Java', 'Bachelor of Engineering In Computers', 'Kishore.Srinivas@ibm.com', 'tne3@123'), ('A004', 'Mr.', 'ANAND RANGANATHAN', 'Mumbai', 'DotNet', 'Master of Computer Applications', 'Anand.Ranganathan@finolex.com', 'tne4@123'), ('A005', 'Miss.', 'LEELA MENON', 'Kerala', 'Mainframe', 'Bachelor of Engineering In Information Technology', 'Leela.Menon@microsoft.com', 'tne5@123'), ('A006', 'Mrs.', 'ARTI KRISHNAN', 'Pune', 'Testing', 'Master of Computer Applications', 'Arti.Krishnan@cognizant.com', 'tne6@123'), ('A007', 'Mr.', 'PRABHAKAR SHUNMUGHAM', 'Mumbai', 'Java', 'Bachelor of Technology', 'Prabhakar.Shunmugham@honda.com', 'tne7@123');
INSERT INTO Module_Info(Module_Id, Module_Name, Module_Duration) VALUES('O10SQL', 'Oracle 10g SQL', 16), ('O10PLSQL', 'Oracle 10g PL/ SQL', 16), ('J2SE', 'Core Java SE 1.6', 288), ('J2EE', 'Advanced Java EE 1.6', 80), ('JAVAFX', 'JavaFX 2.1', 80), ('DOTNT4', '.Net Framework 4.0', 50), ('SQL2008', 'MS SQl Server 2008', 120);